# syntax=docker/dockerfile:1

FROM python:3.10-buster

# means Python will not try to write .pyc files
ENV PYTHONDONTWRITEBYTECODE=1

# The enviroment variable ensures that the python output is set straight
# to the terminal with out buffering it first
ENV PYTHONUNBUFFERED=1

# Set the working directory to /contato
WORKDIR /contato

# Updates de OS
RUN apt-get update

# Updates de PIP
RUN pip install pip --upgrade

# Copy the current directory contents into the container at /contato
COPY requirements.txt /contato/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt --no-cache-dir

# Cria a pasta dos logs
RUN mkdir log

# Copy the current directory contents into the container at /contato
COPY . /contato/