# Generated by Django 4.0 on 2023-09-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_remove_usuario_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('id_pgto_mercado_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
