# Generated by Django 4.0 on 2023-06-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='Aceite'),
        ),
    ]
