# Generated by Django 4.0 on 2023-09-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='terms',
        ),
    ]
