# Generated by Django 4.0 on 2023-10-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_id', models.CharField(max_length=50, verbose_name='Assinatura ID')),
                ('payer_id', models.CharField(max_length=20, verbose_name='Payer ID')),
                ('date_created', models.DateField(max_length=50, verbose_name='Criado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(max_length=50, verbose_name='Início')),
                ('next_payment_date', models.DateField(max_length=50, verbose_name='Próximo pgto')),
                ('last_modified', models.DateField(max_length=50, verbose_name='Atualizado')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
