# syntax=docker/dockerfile:1

FROM nginx:latest

RUN rm -f /etc/nginx/conf.d/*

# Config
COPY ./gzip.conf /etc/nginx/gzip.conf
COPY ./nginx.conf /etc/nginx/nginx.conf

# make all files belong to the nginx user
RUN chown nginx:nginx /usr/share/nginx/html