# Generated by Django 4.0 on 2023-06-05 20:43

import cards.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcf', models.FileField(blank=True, null=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vcf'])], verbose_name='VCF')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='QR Code')),
                ('nome_display', models.CharField(max_length=50, verbose_name='Nome display')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True, verbose_name='Slug')),
                ('img_perfil', models.FileField(blank=True, null=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Foto perfil')),
                ('cargo', models.CharField(blank=True, max_length=50, verbose_name='Cargo')),
                ('telefone', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
                ('whatsapp', models.CharField(max_length=11, verbose_name='Whatsapp')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('logotipo', models.FileField(blank=True, null=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Logotipo')),
                ('slug_empresa', models.SlugField(editable=False, max_length=200, unique=True, verbose_name='Slug da Empresa')),
                ('site', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Site')),
                ('facebook', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Linkedin')),
                ('youtube', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Youtube')),
                ('tik_tok', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Tik_tok')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateField(auto_now=True, verbose_name='Atualizado')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Estado')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='TipoConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de conteúdo',
                'verbose_name_plural': 'Tipos de conteúdo',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Subcategoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='cards.categoria', verbose_name='Subcategoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Município')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Imagem')),
                ('link', models.URLField(blank=True, max_length=1000, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Link')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='cards.card', verbose_name='card')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='cards.tipoconteudo', verbose_name='Tipo')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='card',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='card',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.municipio', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='card',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='usuarios.usuario', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='card',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.subcategoria', verbose_name='Subcategoria'),
        ),
    ]
