# Generated by Django 4.0 on 2024-05-06 23:26

import cards.models
import cards.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CodigoPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Código de país',
                'verbose_name_plural': 'Códigos de países',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Estado')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='TipoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de anúncio',
                'verbose_name_plural': 'Tipos de anúncio',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Subcategoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='cards.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Município')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[cards.utils.valida_cnpj], verbose_name='CNPJ')),
                ('slug', models.SlugField(editable=False, verbose_name='Slug')),
                ('criada', models.DateField(auto_now_add=True, verbose_name='Criada')),
                ('atualizada', models.DateField(auto_now=True, verbose_name='Atualizada')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='usuarios.usuario', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcf', models.FileField(blank=True, null=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vcf'])], verbose_name='VCF')),
                ('endereco', models.CharField(blank=True, max_length=500, verbose_name='Endereço')),
                ('site', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Site')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='QR Code')),
                ('nome_display', models.CharField(max_length=50, verbose_name='Nome display')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True, verbose_name='Slug')),
                ('img_perfil', models.FileField(upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Foto perfil')),
                ('cargo', models.CharField(blank=True, max_length=50, verbose_name='Cargo')),
                ('modelo', models.CharField(max_length=1, verbose_name='Modelo')),
                ('cor', models.CharField(default='#212529', max_length=7, verbose_name='Cor de fundo')),
                ('instagram', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Instagram')),
                ('whatsapp', models.CharField(max_length=20, unique=True, verbose_name='Whatsapp')),
                ('tik_tok', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Tik_tok')),
                ('linkedin', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Linkedin')),
                ('facebook', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Youtube')),
                ('conteudo_pesquisavel', models.TextField(default='', editable=False, verbose_name='Conteúdo pesquisável')),
                ('logotipo', models.FileField(blank=True, null=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Logotipo')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.categoria', verbose_name='Categoria')),
                ('cod_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.codigopais', verbose_name='Código do país')),
                ('empresa', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.empresa', verbose_name='Empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.estado', verbose_name='Estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.municipio', verbose_name='Município')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='usuarios.usuario', verbose_name='Proprietário')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.subcategoria', verbose_name='Subcategoria')),
                ('usuario_do_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_do_usuario', to='usuarios.usuario', verbose_name='Usuário do card')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Imagem')),
                ('link', models.URLField(blank=True, max_length=1000, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Link')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='cards.card', verbose_name='card')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='cards.tipoanuncio', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
            },
        ),
    ]
