# Generated by Django 4.0 on 2022-10-05 01:58

import cards.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='facebook',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='card',
            name='img_perfil',
            field=models.FileField(blank=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Foto perfil'),
        ),
        migrations.AlterField(
            model_name='card',
            name='instagram',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='card',
            name='linkedin',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logotipo',
            field=models.FileField(blank=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Logotipo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='site',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Site'),
        ),
    ]
