# Generated by Django 5.0.6 on 2024-07-04 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='cards.card', verbose_name='Card')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
