# Generated by Django 4.0 on 2024-04-29 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='usuarios.usuario', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='cards.card', verbose_name='card'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='cards.tipoconteudo', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='card',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='card',
            name='cod_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.codigopais', verbose_name='Código do país'),
        ),
        migrations.AddField(
            model_name='card',
            name='empresa',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='card',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='card',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.municipio', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='card',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='usuarios.usuario', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='card',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.subcategoria', verbose_name='Subcategoria'),
        ),
    ]
