# Generated by Django 4.0 on 2022-10-20 00:29

import cards.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='produtos',
            field=models.ImageField(blank=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Produtos'),
        ),
        migrations.AddField(
            model_name='card',
            name='produtos_link',
            field=models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Produtos link'),
        ),
        migrations.AddField(
            model_name='card',
            name='promocao',
            field=models.ImageField(blank=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Promoção'),
        ),
        migrations.AddField(
            model_name='card',
            name='promocao_link',
            field=models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Promoção link'),
        ),
        migrations.AddField(
            model_name='card',
            name='servicos',
            field=models.ImageField(blank=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Serviços'),
        ),
        migrations.AddField(
            model_name='card',
            name='servicos_link',
            field=models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Serviços link'),
        ),
        migrations.AddField(
            model_name='card',
            name='slide1_link',
            field=models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Slide 1 link'),
        ),
        migrations.AddField(
            model_name='card',
            name='slide2_link',
            field=models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Slide 2 link'),
        ),
        migrations.AddField(
            model_name='card',
            name='slide3_link',
            field=models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Slide 3 link'),
        ),
        migrations.AddField(
            model_name='card',
            name='youtube',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Youtube'),
        ),
    ]
