# Generated by Django 4.0 on 2023-10-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='usuarios.usuario', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='card',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.subcategoria', verbose_name='Subcategoria'),
        ),
    ]
