# Generated by Django 4.0 on 2022-11-01 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='vendedores',
            field=models.ManyToManyField(blank=True, related_name='empresa_vendedores', to=settings.AUTH_USER_MODEL, verbose_name='Vendedores'),
        ),
    ]
