# Generated by Django 4.2 on 2023-08-30 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='conteudo_pesquisavel',
            field=models.TextField(default='', editable=False, verbose_name='Conteúdo pesquisável'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='cards.categoria', verbose_name='Categoria'),
        ),
    ]
