# Generated by Django 4.0 on 2022-08-13 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='gerente',
            field=models.ManyToManyField(related_name='empresas', to=settings.AUTH_USER_MODEL, verbose_name='Gerente'),
        ),
        migrations.AddField(
            model_name='card',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.empresa', verbose_name='Empresa'),
        ),
    ]
