# Generated by Django 4.0 on 2024-05-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(editable=False, verbose_name='Slug'),
        ),
    ]
