# Generated by Django 4.0 on 2022-10-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_produtos_card_produtos_link_card_promocao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='promocao',
            new_name='promocoes',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='promocao_link',
            new_name='promocoes_link',
        ),
        migrations.AlterField(
            model_name='card',
            name='youtube',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Youtube'),
        ),
    ]
