# Generated by Django 4.0 on 2022-08-22 19:36

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, upload_to=cards.models.get_image_path, verbose_name='Logotipo'),
        ),
    ]
