# Generated by Django 4.0 on 2022-10-05 13:01

import cards.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_facebook_alter_card_img_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='vcard',
            field=models.FileField(blank=True, upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vcf'])], verbose_name='Vcard'),
        ),
    ]
