# Generated by Django 4.0 on 2024-04-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='card',
            name='whatsapp',
            field=models.CharField(max_length=15, unique=True, verbose_name='Whatsapp'),
        ),
    ]
