# Generated by Django 4.0 on 2023-10-02 21:08

import cards.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_conteudo_pesquisavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='img_perfil',
            field=models.FileField(default='media/966f78856a02405295a63010cc8814be/ayla-memoji.png', upload_to=cards.models.get_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'svg'])], verbose_name='Foto perfil'),
            preserve_default=False,
        ),
    ]
