# Generated by Django 4.0 on 2023-11-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='nome',
            field=models.CharField(default='nome', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
