# Generated by Django 4.0 on 2024-05-24 10:29

import cards.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[cards.utils.valida_cnpj], verbose_name='CNPJ'),
        ),
    ]
