# Generated by Django 4.0 on 2022-11-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_empresa_vendedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='youtube',
        ),
    ]
