# Generated by Django 4.0 on 2022-10-15 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_vcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='facebook',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='card',
            name='instagram',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='card',
            name='linkedin',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Linkedin'),
        ),
    ]
