# Generated by Django 4.0 on 2022-09-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='nome',
            field=models.CharField(default='tiberio-mendonca', editable=False, max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/', verbose_name='Logotipo'),
        ),
    ]
