# Generated by Django 4.0 on 2023-11-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_conteudo_descricao_conteudo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='telefone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='card',
            name='whatsapp',
            field=models.CharField(max_length=15, verbose_name='Whatsapp'),
        ),
    ]
