# Generated by Django 5.0.6 on 2024-07-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_avaliacao_options_alter_avaliacao_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='ativo',
        ),
        migrations.AddField(
            model_name='card',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='Público'),
        ),
    ]
