# Generated by Django 4.0 on 2023-12-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cor',
            field=models.CharField(default='#212529', max_length=7, verbose_name='Cor de fundo'),
        ),
    ]
