# Generated by Django 4.0 on 2024-06-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_empresa_cnpj_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='whatsapp',
            field=models.CharField(max_length=15, unique=True, verbose_name='Whatsapp'),
        ),
    ]
