# Generated by Django 4.0 on 2024-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_empresa_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=200, verbose_name='Nome Fantasia'),
        ),
    ]
