# Generated by Django 4.0 on 2024-04-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_telefone_alter_card_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Código de país',
                'verbose_name_plural': 'Códigos de países',
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='whatsapp',
            field=models.CharField(max_length=20, unique=True, verbose_name='Whatsapp'),
        ),
    ]
