# Generated by Django 4.0 on 2023-11-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_telefone_alter_card_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='modelo',
            field=models.CharField(default='A', max_length=1, verbose_name='Modelo'),
            preserve_default=False,
        ),
    ]
