# Generated by Django 4.0 on 2022-09-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_nome_alter_empresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
