# Generated by Django 4.0 on 2024-04-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_codigopais_alter_card_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cod_pais',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.codigopais', verbose_name='Código do país'),
            preserve_default=False,
        ),
    ]
