# Generated by Django 4.0 on 2022-09-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='nome',
        ),
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default='tiberio-mendonca', max_length=200, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
