# Generated by Django 4.0 on 2023-11-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='endereco',
            field=models.CharField(default='goiania', max_length=500, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
