# Generated by Django 4.0 on 2022-09-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_card_nome_card_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, verbose_name='Slug'),
        ),
    ]
