# Generated by Django 4.0 on 2023-11-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='endereco',
            field=models.CharField(blank=True, max_length=500, verbose_name='Endereço'),
        ),
    ]
