# Generated by Django 4.0 on 2022-09-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('cards', '0007_alter_card_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='usuarios.usuario', verbose_name='Usuário'),
            preserve_default=False,
        ),
    ]
