# Generated by Django 4.0 on 2022-09-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='primeiro_nome',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ultimo_nome',
        ),
    ]
