# Generated by Django 4.0 on 2022-09-26 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0009_remove_card_primeiro_nome_remove_card_ultimo_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='gerente',
        ),
        migrations.AddField(
            model_name='empresa',
            name='gerentes',
            field=models.ManyToManyField(related_name='empresa_gerente', to=settings.AUTH_USER_MODEL, verbose_name='Gerente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='vendedores',
            field=models.ManyToManyField(related_name='empresa_usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Vendedores'),
        ),
    ]
