# Generated by Django 4.0 on 2022-09-26 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0010_remove_empresa_gerente_empresa_gerentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='gerentes',
            field=models.ManyToManyField(related_name='empresa_gerentes', to=settings.AUTH_USER_MODEL, verbose_name='Gerente'),
        ),
    ]
