# Generated by Django 4.0 on 2022-09-26 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0012_alter_empresa_gerentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='vendedores',
            field=models.ManyToManyField(related_name='empresa_vendedores', to=settings.AUTH_USER_MODEL, verbose_name='Vendedores'),
        ),
    ]
