# Generated by Django 4.0 on 2022-09-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_alter_empresa_vendedores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterField(
            model_name='card',
            name='facebook',
            field=models.URLField(verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='card',
            name='instagram',
            field=models.URLField(verbose_name='Instagram'),
        ),
    ]
