# Generated by Django 4.0 on 2022-09-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_alter_card_options_alter_card_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='linkedin',
            field=models.URLField(default='https://linkedin.com/in/tiberiodamaso/', verbose_name='Linkedin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='site',
            field=models.URLField(default='https://google.com/', verbose_name='Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='img_perfil',
            field=models.ImageField(blank=True, default='', null=True, upload_to='<function get_image_path at 0x10531b2e0>/cards/', verbose_name='Foto perfil'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, upload_to='<function get_image_path at 0x10531b2e0>/logos/', verbose_name='Logotipo'),
        ),
    ]
