# Generated by Django 4.0 on 2022-09-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_card_linkedin_empresa_site_alter_card_img_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logotipo',
            field=models.FileField(blank=True, upload_to='<function get_image_path at 0x10d43f2e0>/logos/', verbose_name='Logotipo2'),
        ),
        migrations.AlterField(
            model_name='card',
            name='img_perfil',
            field=models.ImageField(blank=True, default='', null=True, upload_to='<function get_image_path at 0x10d43f2e0>/cards/', verbose_name='Foto perfil'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, upload_to='<function get_image_path at 0x10d43f2e0>/logos/', verbose_name='Logotipo'),
        ),
    ]
