# Generated by Django 4.0 on 2022-09-28 13:21

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_empresa_logotipo_alter_card_img_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='img_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto perfil'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, upload_to=cards.models.get_image_path, verbose_name='Logotipo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logotipo',
            field=models.FileField(blank=True, upload_to=cards.models.get_image_path, verbose_name='Logotipo2'),
        ),
    ]
