# Generated by Django 4.0 on 2022-09-28 20:45

import cards.models
import cards.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_alter_card_img_perfil_alter_empresa_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='logo',
        ),
        migrations.AlterField(
            model_name='card',
            name='img_perfil',
            field=models.FileField(blank=True, upload_to=cards.models.get_image_path, validators=[cards.utils.validate_file_extension], verbose_name='Foto perfil'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logotipo',
            field=models.FileField(blank=True, upload_to=cards.models.get_image_path, validators=[cards.utils.validate_file_extension], verbose_name='Logotipo'),
        ),
    ]
