# Generated by Django 4.0 on 2024-05-06 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_id', models.CharField(max_length=50, verbose_name='Assinatura ID')),
                ('payer_id', models.CharField(max_length=20, verbose_name='Payer ID')),
                ('date_created', models.DateField(max_length=50, verbose_name='Criado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(max_length=50, verbose_name='Início')),
                ('next_payment_date', models.DateField(max_length=50, verbose_name='Próximo pgto')),
                ('last_modified', models.DateField(max_length=50, verbose_name='Atualizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='usuarios.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='CartaoPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_id', models.CharField(max_length=50, verbose_name='Assinatura ID')),
                ('payer_id', models.CharField(max_length=20, verbose_name='Payer ID')),
                ('date_created', models.DateField(max_length=50, verbose_name='Criado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(max_length=50, verbose_name='Início')),
                ('next_payment_date', models.DateField(max_length=50, verbose_name='Próximo pgto')),
                ('last_modified', models.DateField(max_length=50, verbose_name='Atualizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoespj', to='usuarios.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cartão PJ',
                'verbose_name_plural': 'Cartões PJ',
            },
        ),
        migrations.CreateModel(
            name='CartaoPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_id', models.CharField(max_length=50, verbose_name='Pagamento ID')),
                ('payer_id', models.CharField(max_length=20, verbose_name='Payer ID')),
                ('date_created', models.DateField(max_length=50, verbose_name='Criado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('authorization_code', models.CharField(max_length=100, verbose_name='Códito de autorização')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoespf', to='usuarios.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cartão PF',
                'verbose_name_plural': 'Cartões PF',
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_id', models.CharField(max_length=50, verbose_name='Pagamento ID')),
                ('payer_id', models.CharField(max_length=20, verbose_name='Payer ID')),
                ('date_created', models.DateField(max_length=50, verbose_name='Criado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('authorization_code', models.CharField(max_length=100, verbose_name='Códito de autorização')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='usuarios.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
            },
        ),
    ]
