# Generated by Django 4.0 on 2024-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_id', models.CharField(max_length=50, verbose_name='Pagamento ID')),
                ('payer_id', models.CharField(max_length=20, verbose_name='Payer ID')),
                ('date_created', models.DateField(max_length=50, verbose_name='Criado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('authorization_code', models.CharField(max_length=100, verbose_name='Códito de autorização')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
            },
        ),
        migrations.CreateModel(
            name='CartaoPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_id', models.CharField(max_length=50, verbose_name='Pagamento ID')),
                ('payer_id', models.CharField(max_length=20, verbose_name='Payer ID')),
                ('date_created', models.DateField(max_length=50, verbose_name='Criado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('authorization_code', models.CharField(max_length=100, verbose_name='Códito de autorização')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Cartão PF',
                'verbose_name_plural': 'Cartões PF',
            },
        ),
        migrations.CreateModel(
            name='CartaoPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_id', models.CharField(max_length=50, verbose_name='Assinatura ID')),
                ('payer_id', models.CharField(max_length=20, verbose_name='Payer ID')),
                ('date_created', models.DateField(max_length=50, verbose_name='Criado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(max_length=50, verbose_name='Início')),
                ('next_payment_date', models.DateField(max_length=50, verbose_name='Próximo pgto')),
                ('last_modified', models.DateField(max_length=50, verbose_name='Atualizado')),
            ],
            options={
                'verbose_name': 'Cartão PJ',
                'verbose_name_plural': 'Cartões PJ',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_id', models.CharField(max_length=50, verbose_name='Assinatura ID')),
                ('payer_id', models.CharField(max_length=20, verbose_name='Payer ID')),
                ('date_created', models.DateField(max_length=50, verbose_name='Criado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(max_length=50, verbose_name='Início')),
                ('next_payment_date', models.DateField(max_length=50, verbose_name='Próximo pgto')),
                ('last_modified', models.DateField(max_length=50, verbose_name='Atualizado')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
    ]
