# Generated by Django 5.0.6 on 2024-06-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_id', models.CharField(max_length=50, verbose_name='Pagamento ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
            },
        ),
        migrations.CreateModel(
            name='CartaoPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_id', models.CharField(max_length=50, verbose_name='Pagamento ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoespf', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cartão PF',
                'verbose_name_plural': 'Cartões PF',
            },
        ),
        migrations.CreateModel(
            name='CartaoPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_id', models.CharField(max_length=50, verbose_name='Assinatura ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('stripe_customer', models.CharField(max_length=100, verbose_name='Stripe customer')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('cancelamento', models.DateField(blank=True, default=None, null=True, verbose_name='Cancelamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoespj', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cartão PJ',
                'verbose_name_plural': 'Cartões PJ',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_id', models.CharField(max_length=50, verbose_name='Assinatura ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('stripe_customer', models.CharField(max_length=100, verbose_name='Stripe customer')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('cancelamento', models.DateField(blank=True, default=None, null=True, verbose_name='Cancelamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
    ]
