# Generated by Django 4.0 on 2024-05-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='usuarios.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='cartaopj',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoespj', to='usuarios.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='cartaopf',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoespf', to='usuarios.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='ad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='usuarios.usuario', verbose_name='Usuário'),
        ),
    ]
