# Generated by Django 4.0 on 2023-12-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='usuarios.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='usuarios.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='usuarios.usuario', verbose_name='Usuário'),
        ),
    ]
