# Generated by Django 4.0 on 2024-05-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_id', models.CharField(max_length=50, verbose_name='Pagamento ID')),
                ('payer_id', models.CharField(max_length=20, verbose_name='Payer ID')),
                ('date_created', models.DateField(max_length=50, verbose_name='Criado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('authorization_code', models.CharField(max_length=100, verbose_name='Códito de autorização')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='usuarios.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
            },
        ),
        migrations.DeleteModel(
            name='Anuncio',
        ),
    ]
