# Generated by Django 4.0 on 2023-12-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='authorization_code',
            field=models.CharField(default='1', max_length=100, verbose_name='Códito de autorização'),
            preserve_default=False,
        ),
    ]
