# Generated by Django 4.0 on 2024-05-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartao',
            new_name='CartaoPF',
        ),
        migrations.AlterModelOptions(
            name='cartaopf',
            options={'verbose_name': 'Cartão PF', 'verbose_name_plural': 'Cartões PF'},
        ),
    ]
