# Generated by Django 4.0 on 2024-05-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('compras', '0003_rename_cartao_cartaopf_alter_cartaopf_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaopf',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoespf', to='usuarios.usuario', verbose_name='Usuário'),
        ),
    ]
