# Generated by Django 4.0 on 2024-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
