# Generated by Django 4.0 on 2024-06-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_pagamento_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaopf',
            name='authorization_code',
        ),
        migrations.RemoveField(
            model_name='cartaopf',
            name='payer_id',
        ),
        migrations.AlterField(
            model_name='cartaopf',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='cartaopj',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
    ]
