# Generated by Django 4.0 on 2024-06-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_cartaopf_authorization_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartaopj',
            old_name='assinatura_id',
            new_name='pagamento_id',
        ),
        migrations.RenameField(
            model_name='relatorio',
            old_name='assinatura_id',
            new_name='pagamento_id',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='authorization_code',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='payer_id',
        ),
        migrations.RemoveField(
            model_name='cartaopj',
            name='payer_id',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='payer_id',
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
    ]
