# Generated by Django 4.0 on 2024-06-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_rename_assinatura_id_cartaopj_pagamento_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio',
            old_name='pagamento_id',
            new_name='assinatura_id',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='next_payment_date',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='start_date',
        ),
    ]
