# Generated by Django 4.0 on 2024-06-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_rename_pagamento_id_relatorio_assinatura_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartaopj',
            old_name='pagamento_id',
            new_name='assinatura_id',
        ),
        migrations.RemoveField(
            model_name='cartaopj',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='cartaopj',
            name='next_payment_date',
        ),
        migrations.RemoveField(
            model_name='cartaopj',
            name='start_date',
        ),
    ]
