# Generated by Django 4.0 on 2024-06-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_rename_pagamento_id_cartaopj_assinatura_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
