# Generated by Django 4.0 on 2024-06-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_delete_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaopj',
            name='stripe_customer',
            field=models.CharField(default='teste', max_length=100, verbose_name='Stripe customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatorio',
            name='stripe_customer',
            field=models.CharField(default='teste', max_length=100, verbose_name='Stripe customer'),
            preserve_default=False,
        ),
    ]
