# Generated by Django 4.0 on 2024-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_cartaopj_stripe_customer_relatorio_stripe_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaopj',
            name='cancelamento',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Cancelamento'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='cancelamento',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Cancelamento'),
        ),
    ]
